const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.Flash,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Behaviors.solid,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.gamepad,
		C3.Plugins.Touch,
		C3.Behaviors.Platform,
		C3.Behaviors.Timer,
		C3.Plugins.Arr,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Browser.Acts.Close,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Audio.Cnds.IsAnyPlaying,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Acts.RestoreObjectTimescale,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.gamepad.Cnds.OnButtonUp,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Exps.len,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Cnds.TriggerOnce
	];
};
self.C3_JsPropNameTable = [
	{pontos_de_vida: 0},
	{Hud_vida: 0},
	{Debug: 0},
	{Debug2: 0},
	{Caixa_dialogo: 0},
	{Texto_dialogo: 0},
	{boss_hp: 0},
	{boss_hp_background: 0},
	{Dialogo_nome_personagem: 0},
	{text_boss: 0},
	{Flash: 0},
	{Ready: 0},
	{direcao: 0},
	{Bullet: 0},
	{Options_Cursor: 0},
	{funcao: 0},
	{botao_mobile_atira: 0},
	{botao_mobile_direita: 0},
	{botao_mobile_esquerda: 0},
	{botao_mobile_pula: 0},
	{vivo: 0},
	{nome_grafico: 0},
	{invulneravel: 0},
	{ativo: 0},
	{solta_refil_de_vida: 0},
	{Cou_Hitbox: 0},
	{Blob_hitbox: 0},
	{direcao_vertical: 0},
	{altura_inicial: 0},
	{Pruu_hitbox: 0},
	{Rotate: 0},
	{Cou: 0},
	{Blob: 0},
	{Pruu: 0},
	{Cenario_Underworld: 0},
	{Solid: 0},
	{Chão: 0},
	{Fundo2: 0},
	{Fundo_prédios: 0},
	{offset: 0},
	{Nuvens: 0},
	{Parede: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{esquerda_ou_direita: 0},
	{Parede_boss: 0},
	{Chão3: 0},
	{Chão2: 0},
	{destrava_camera: 0},
	{Fronteira_boss: 0},
	{trava_camera: 0},
	{Audio: 0},
	{Keyboard: 0},
	{Browser: 0},
	{Gamepad: 0},
	{Touch: 0},
	{brilho: 0},
	{Cubics: 0},
	{estado: 0},
	{invencivel: 0},
	{esta_correndo: 0},
	{timer_corrida: 0},
	{morto: 0},
	{Platform: 0},
	{Timer: 0},
	{Player: 0},
	{Soco: 0},
	{Cubics_Dialogo: 0},
	{fade_out: 0},
	{FadeIn: 0},
	{Texto_titulo: 0},
	{Titulo: 0},
	{Logo: 0},
	{Texto_titulo_versao: 0},
	{dialogos_chefe_fase1: 0},
	{Focalan: 0},
	{contador_bolas: 0},
	{contador_bolas_destruidas: 0},
	{Focalan_hitbox: 0},
	{BolaDePraia: 0},
	{BolaDePraia_hitbox: 0},
	{Focalan_Dialogo: 0},
	{Arbusto: 0},
	{BancoDePraça: 0},
	{Construção: 0},
	{Pedra: 0},
	{PlacaAtenção: 0},
	{PlaceDireita: 0},
	{PlaceObras: 0},
	{PlaceProibidoSubir: 0},
	{Poste: 0},
	{Árvore: 0},
	{texto_vidas: 0},
	{texto_game_over: 0},
	{RefilDeVida: 0},
	{estado_fase: 0},
	{scrollx_boss: 0},
	{pausado: 0},
	{opcao_selecionada: 0},
	{Tween: 0},
	{Controller: 0},
	{teste: 0},
	{Text: 0},
	{Text2: 0},
	{Text3: 0},
	{debug_credito: 0},
	{Text4: 0},
	{Text5: 0},
	{Nome_Pruu: 0},
	{Text6: 0},
	{Fade: 0},
	{Options: 0},
	{Options_Resume: 0},
	{Options_Exit: 0},
	{Camera: 0},
	{Inimigo: 0},
	{Inimigo_grafico: 0},
	{Boss: 0},
	{ignorando_inputs: 0},
	{vidas: 0},
	{debug: 0},
	{velocidade_cubics: 0},
	{socos_na_tela: 0},
	{movimento_horizontal: 0},
	{input_direita: 0},
	{input_esquerda: 0},
	{camera_vertical_travado: 0},
	{altura_camera_travada: 0},
	{camera_speed: 0},
	{vertical_offset: 0},
	{max_camera_distance: 0},
	{linha_de_dialogo: 0}
];

self.InstanceType = {
	Hud_vida: class extends self.ISpriteInstance {},
	Debug: class extends self.ITextInstance {},
	Debug2: class extends self.ITextInstance {},
	Caixa_dialogo: class extends self.ITiledBackgroundInstance {},
	Texto_dialogo: class extends self.ITextInstance {},
	boss_hp: class extends self.ISpriteInstance {},
	boss_hp_background: class extends self.ISpriteInstance {},
	Dialogo_nome_personagem: class extends self.ITextInstance {},
	text_boss: class extends self.ITextInstance {},
	Ready: class extends self.ITextInstance {},
	Options_Cursor: class extends self.ISpriteInstance {},
	botao_mobile_atira: class extends self.ISpriteInstance {},
	botao_mobile_direita: class extends self.ISpriteInstance {},
	botao_mobile_esquerda: class extends self.ISpriteInstance {},
	botao_mobile_pula: class extends self.ISpriteInstance {},
	Cou_Hitbox: class extends self.ISpriteInstance {},
	Blob_hitbox: class extends self.ISpriteInstance {},
	Pruu_hitbox: class extends self.ISpriteInstance {},
	Cou: class extends self.ISpriteInstance {},
	Blob: class extends self.ISpriteInstance {},
	Pruu: class extends self.ISpriteInstance {},
	Cenario_Underworld: class extends self.ISpriteInstance {},
	Chão: class extends self.ITiledBackgroundInstance {},
	Fundo2: class extends self.ITiledBackgroundInstance {},
	Fundo_prédios: class extends self.ITiledBackgroundInstance {},
	Nuvens: class extends self.ITiledBackgroundInstance {},
	Parede: class extends self.ITiledBackgroundInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Parede_boss: class extends self.ITiledBackgroundInstance {},
	Chão3: class extends self.ITiledBackgroundInstance {},
	Chão2: class extends self.ITiledBackgroundInstance {},
	destrava_camera: class extends self.ISpriteInstance {},
	Fronteira_boss: class extends self.ISpriteInstance {},
	trava_camera: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Cubics: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Soco: class extends self.ISpriteInstance {},
	Cubics_Dialogo: class extends self.ISpriteInstance {},
	FadeIn: class extends self.ITiledBackgroundInstance {},
	Texto_titulo: class extends self.ITextInstance {},
	Titulo: class extends self.ITiledBackgroundInstance {},
	Logo: class extends self.ITiledBackgroundInstance {},
	Texto_titulo_versao: class extends self.ITextInstance {},
	dialogos_chefe_fase1: class extends self.IArrayInstance {},
	Focalan: class extends self.ISpriteInstance {},
	Focalan_hitbox: class extends self.ISpriteInstance {},
	BolaDePraia: class extends self.ISpriteInstance {},
	BolaDePraia_hitbox: class extends self.ISpriteInstance {},
	Focalan_Dialogo: class extends self.ISpriteInstance {},
	Arbusto: class extends self.ISpriteInstance {},
	BancoDePraça: class extends self.ISpriteInstance {},
	Construção: class extends self.ISpriteInstance {},
	Pedra: class extends self.ISpriteInstance {},
	PlacaAtenção: class extends self.ISpriteInstance {},
	PlaceDireita: class extends self.ISpriteInstance {},
	PlaceObras: class extends self.ISpriteInstance {},
	PlaceProibidoSubir: class extends self.ISpriteInstance {},
	Poste: class extends self.ISpriteInstance {},
	Árvore: class extends self.ISpriteInstance {},
	texto_vidas: class extends self.ITextInstance {},
	texto_game_over: class extends self.ITextInstance {},
	RefilDeVida: class extends self.ISpriteInstance {},
	Controller: class extends self.ISpriteInstance {},
	teste: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	debug_credito: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Nome_Pruu: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	Fade: class extends self.ISpriteInstance {},
	Options: class extends self.ISpriteInstance {},
	Options_Resume: class extends self.ITextInstance {},
	Options_Exit: class extends self.ITextInstance {},
	Camera: class extends self.ISpriteInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	Inimigo_grafico: class extends self.ISpriteInstance {},
	Boss: class extends self.ISpriteInstance {}
}